-- Wavo AI support: server-only usage accounting, idempotency, and a small
-- first-party knowledge base. The Edge Function owns access to these tables.

create table if not exists public.support_ai_requests (
  message_id uuid primary key references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  input_chars integer not null default 0 check (input_chars >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  model text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  error_code text
);

create index if not exists support_ai_requests_user_created_idx
  on public.support_ai_requests (user_id, created_at desc);
create index if not exists support_ai_requests_created_idx
  on public.support_ai_requests (created_at desc);
create index if not exists support_ai_requests_status_created_idx
  on public.support_ai_requests (status, created_at desc);

alter table public.support_ai_requests enable row level security;
revoke all on table public.support_ai_requests from anon, authenticated;

comment on table public.support_ai_requests is
  'Server-only accounting/idempotency for Wavo AI support. No client policies by design.';

create table if not exists public.support_ai_knowledge (
  id bigint generated by default as identity primary key,
  topic text not null unique,
  content text not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.support_ai_knowledge enable row level security;
revoke all on table public.support_ai_knowledge from anon, authenticated;

insert into public.support_ai_knowledge (topic, content) values
('account_signin', 'Sign in with the email address and password used at signup, not the username. Saved accounts can be checked from avatar > Settings > Account > Saved accounts.'),
('password_reset', 'There is no self-serve password reset in Wavo yet. The user should contact support from the email address on the account.'),
('username_change', 'Usernames can be changed in Settings > Profile. Usernames are unique.'),
('account_delete', 'Account deletion is in Settings > Account > Danger zone > Delete account. It erases the profile, messages, friends and groups and cannot be undone.'),
('blocking_reporting', 'Block from the chat menu. Reports can be made from a message menu or a profile. Reporting and blocking are separate.'),
('notifications', 'Notifications require browser or phone permission. If permission was denied, re-enable Wavo in browser site settings or phone notification settings and reload. On iPhone web notifications require Wavo to be added to the Home Screen and opened from there.'),
('streaks', 'Streaks count days where both friends send something and roll over at midnight in the user timezone.'),
('premium', 'Premium is purchased on the Wavo website and payments are processed by Stripe. If benefits do not appear, reload first. Billing cancellation/refund requests currently require support.'),
('bugs', 'For bug reports, collect what the user tapped, what they expected, what happened instead, device/browser or OS, and screenshots when available. Privacy or message-loss bugs are high priority.'),
('product', 'Wavo is a social app with direct messages, groups/spaces, Waves, voice/video calls, notifications, plans, themes, badges and Premium. Do not invent features or settings that are not present in the knowledge base or conversation.')
on conflict (topic) do update
set content = excluded.content,
    active = true,
    updated_at = now();
