-- Secure account recovery and password reset storage.
-- Recovery addresses live outside public profiles so other signed-in users cannot read them.

create table if not exists public.account_recovery (
  user_id uuid primary key references auth.users(id) on delete cascade,
  recovery_email text,
  recovery_email_verified_at timestamptz,
  pending_recovery_email text,
  pending_email_token_hash text unique,
  pending_email_expires_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.account_recovery enable row level security;
drop policy if exists "account recovery own read" on public.account_recovery;
create policy "account recovery own read"
  on public.account_recovery
  for select
  using (auth.uid() = user_id);

revoke all on table public.account_recovery from anon, authenticated;
grant select on table public.account_recovery to authenticated;

create table if not exists public.password_reset_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_tokens_user_idx
  on public.password_reset_tokens (user_id, created_at desc);
create index if not exists password_reset_tokens_expiry_idx
  on public.password_reset_tokens (expires_at);

alter table public.password_reset_tokens enable row level security;
revoke all on table public.password_reset_tokens from anon, authenticated;

create table if not exists public.password_reset_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_attempts_identifier_idx
  on public.password_reset_attempts (identifier_hash, created_at desc);
create index if not exists password_reset_attempts_ip_idx
  on public.password_reset_attempts (ip_hash, created_at desc);

alter table public.password_reset_attempts enable row level security;
revoke all on table public.password_reset_attempts from anon, authenticated;

-- Preserve any legacy real email that was stored on a broadly-readable profile row.
insert into public.account_recovery (user_id, recovery_email, recovery_email_verified_at, updated_at)
select id, lower(btrim(email)), now(), now()
from public.profiles
where email is not null and btrim(email) <> ''
on conflict (user_id) do update
set recovery_email = coalesce(public.account_recovery.recovery_email, excluded.recovery_email),
    recovery_email_verified_at = coalesce(public.account_recovery.recovery_email_verified_at, excluded.recovery_email_verified_at),
    updated_at = now();

-- Recovery addresses should not remain in profiles because profiles are readable by signed-in users.
update public.profiles
set email = null
where email is not null;

-- Keep new profile creation from putting a private recovery address back into profiles.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  uname text;
  bday date;
  internal_account boolean := false;
  recovery_address text;
begin
  uname := coalesce(
    nullif(new.raw_user_meta_data->>'username', ''),
    split_part(new.email, '@', 1)
  );

  internal_account := lower(coalesce(new.raw_user_meta_data->>'is_internal', 'false')) in ('true', '1', 'yes');

  if uname ~* '^test:' then
    internal_account := true;
    uname := btrim(substring(uname from 6));
  end if;

  if uname is null or uname = '' then
    uname := split_part(new.email, '@', 1);
  end if;

  begin
    bday := nullif(new.raw_user_meta_data->>'birthday', '')::date;
  exception when others then
    bday := null;
  end;

  recovery_address := nullif(lower(btrim(new.raw_user_meta_data->>'real_email')), '');

  insert into public.profiles (
    id,
    username,
    first_name,
    last_name,
    email,
    birthday,
    age,
    is_admin,
    is_internal
  )
  values (
    new.id,
    uname,
    nullif(new.raw_user_meta_data->>'first_name', ''),
    nullif(new.raw_user_meta_data->>'last_name', ''),
    null,
    bday,
    case when bday is not null
         then extract(year from age(bday))::int
         else null end,
    false,
    internal_account
  )
  on conflict (id) do nothing;

  if recovery_address is not null then
    insert into public.account_recovery (user_id, pending_recovery_email, updated_at)
    values (new.id, recovery_address, now())
    on conflict (user_id) do update
      set pending_recovery_email = excluded.pending_recovery_email,
          updated_at = now();
  end if;

  return new;
end;
$function$;
